#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR
./download_deps

#ant -buildfile android-store-amazon.xml -Dlogging="true" -Dsoomla.filename="Soomla_debug" all
#ant -buildfile android-store-amazon.xml -Dlogging="false" -Dsoomla.filename="Soomla_release" all
ant -buildfile android-store-amazon.xml -Dsoomla.filename="AndroidStoreAmazon" all
mkdir -p build/billing-services/amazon
mv build/*.jar build/billing-services/amazon/
cp libs/in-app-purchasing-2.0.1.jar build/billing-services/amazon/
cd - > /dev/null
