#!/bin/sh

if [ ! -d libs ];
then
    mkdir libs
fi

if [ ! -f libs/in-app-purchasing-2.0.1.jar ];
then
    curl -L -o libs/in-app-purchasing-2.0.1.jar http://library.soom.la/fetch/android-store-in-app-purchasing/2.0.1?cf=dl_deps
fi